<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?> 
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/bootstrap-3.3.7-dist/css/bootstrap.min.css'); ?>
    </head>

    <body>
        <div id="content">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>

        <button type="button" class="btn btn-primary">Bottone di prova presente in layout</button>

    </body>

</html>
