CREATE TABLE IF NOT EXISTS user (
	id INT NOT NULL PRIMARY KEY UNIQUE KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL, nickname VARCHAR(50) NOT NULL,
	birthdate DATE NOT NULL,
	email TEXT NOT NULL,
	passwordencrypt TEXT NOT NULL,
	passwordsalt TEXT NOT NULL,
	points INT NOT NULL DEFAULT 0,
	captchacount INT NOT NULL DEFAULT 0);
